AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb

Bundler/OrderedGems:
  Enabled: false

Layout/LineLength:
  Max: 150

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Lint/AssignmentInCondition:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 50
  Exclude:
    - spec/**/*_spec.rb

Metrics/ClassLength:
  Max: 300

Metrics/MethodLength:
  Max: 40

Metrics/ParameterLists:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 20

Naming/RescuedExceptionsVariableName:
  Enabled: false

Security/Open:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/Documentation:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/TernaryParentheses:
  EnforcedStyle: require_no_parentheses

Style/SpecialGlobalVars:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
