[tools]
ruby = "3.4.4"
node = "24.0.2"

uv = "0.7.5"
"pipx:aider-chat" = { version = "0.83.1", uvx_args = "--python python3.12" }

"ubi:BurntSushi/xsv" = "0.13.0"
"ubi:dlvhdr/diffnav" = "0.3.1"

"npm:@openai/codex" = "0.1.2505172129"

[settings]
idiomatic_version_file_enable_tools = ["node"]

[settings.ruby]
ruby_build_opts = "RUBY_CONFIGURE_OPTS='--disable-install-doc'"
