[tools]
difftastic = { version = "0.65.0", exe = "difft" }
fzf = "0.66.0"
neovim = "0.11.4"
usage = "2.3.2"

[settings]
auto_install = false
not_found_auto_install = false
env_file = ".env"
disable_hints = ["outdated_bump"]
