[tools]
ruby = "3.4.3"
node = "23.11.0"

uv = "0.7.2"
"pipx:aider-chat" = { version = "0.82.2", uvx_args = "--python python3.12" }

"ubi:BurntSushi/xsv" = "0.13.0"
"ubi:dlvhdr/diffnav" = "0.3.0"

[settings]
idiomatic_version_file_enable_tools = ["node"]

[settings.ruby]
ruby_build_opts = "RUBY_CONFIGURE_OPTS='--disable-install-doc'"
