[tools]
difftastic = "0.63.0"
fzf = "0.62.0"
glow = "2.1.1"
neovim = "0.11.2"
usage = "2.1.1"

[settings]
auto_install = false
not_found_auto_install = false
env_file = ".env"
disable_hints = ["outdated_bump"]
