[tools]
ruby = "3.4.1"
node = "23.6.0"

neovim = "0.10.3"
fzf = "0.57.0"
usage = "2.0.3"
glow = "2.0.0"

"ubi:dlvhdr/diffnav" = "0.3.0"
"ubi:BurntSushi/xsv" = "0.13.0"

[settings]
auto_install = false
not_found_auto_install = false
env_file = '.env'
disable_hints = ["outdated_bump"]

[env]
RUBY_CONFIGURE_OPTS = '--disable-install-doc'
