[tools]
# Languages
ruby = "3.4.7"
node = "25.2.1"

# Tools
"ubi:BurntSushi/xsv" = "0.13.0"
"ubi:dlvhdr/diffnav" = "0.3.1"

# AI tools
"npm:@anthropic-ai/claude-code" = "2.0.49"

[settings]
idiomatic_version_file_enable_tools = ["node"]

[settings.ruby]
ruby_build_opts = "RUBY_CONFIGURE_OPTS='--disable-install-doc'"
