[tools]
difftastic = { version = "0.67.0", exe = "difft" }
fzf = "0.67.0"
neovim = "0.11.5"
usage = "2.8.0"

[settings]
auto_install = false
not_found_auto_install = false
env_file = ".env"
disable_hints = ["outdated_bump"]
