[tools]
# Languages
ruby = "3.4.8"
node = "25.2.1"

# Tools
"npm:@anthropic-ai/claude-code" = "2.0.76"
"ubi:dlvhdr/diffnav" = "0.3.1"

[settings]
idiomatic_version_file_enable_tools = ["node"]

[settings.ruby]
ruby_build_opts = "RUBY_CONFIGURE_OPTS='--disable-install-doc'"
