[tools]
# Languages
ruby = "3.4.5"
node = "24.4.1"

# Tools
"ubi:BurntSushi/xsv" = "0.13.0"
"ubi:dlvhdr/diffnav" = "0.3.1"

# AI tools
uv = "0.8.3"
"pipx:aider-chat" = { version = "0.85.2", uvx_args = "--python python3.12" }
"ubi:sst/opencode" = "0.3.81"
"npm:@anthropic-ai/claude-code" = "1.0.62"

[settings]
idiomatic_version_file_enable_tools = ["node"]

[settings.ruby]
ruby_build_opts = "RUBY_CONFIGURE_OPTS='--disable-install-doc'"
