[tools]
# Languages
ruby = "4.0.0"
node = "25.2.1"

# Tools
"npm:@anthropic-ai/claude-code" = "2.1.5"
"github:dlvhdr/diffnav" = "0.4.0"

[settings]
idiomatic_version_file_enable_tools = ["node"]

[settings.ruby]
ruby_build_opts = "RUBY_CONFIGURE_OPTS='--disable-install-doc'"
