[tools]
# Languages
ruby = "4.0.1"
node = "25.6.1"

# Tools
"github:dlvhdr/diffnav" = "0.9.0"

[settings]
idiomatic_version_file_enable_tools = ["node"]

[settings.ruby]
ruby_build_opts = "RUBY_CONFIGURE_OPTS='--disable-install-doc'"
