[tools]
fzf = "0.55.0"
lazygit = "0.44.1"
node = "22.9.0"
ruby = "3.3.5"
glow = "2.0.0"
neovim = "0.10.2"
usage = "0.8.4"

[settings]
not_found_auto_install = false

[env]
RUBY_CONFIGURE_OPTS = '--disable-install-doc'
